apiVersion: v1
kind: Secret
metadata:
  name: telegraf-secrets
type: Opaque
stringData:
  INFLUX_URL: http://influxdb:8086
  INFLUX_TOKEN: mytoken #Put your token here!
  INFLUX_ORG: nathanorg # Put your organization here!
  INFLUX_BUCKET: kube-bucket # Put your bucket name here!
