version: '3'
services: 
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - telegraf-influx-network
    environment:
    - INFLUX_TOKEN=mytoken #Put Your token here!
    - INFLUX_ORG=nathanorg 
    - INFLUX_BUCKET=nathanorg-bucket 
    ports:
    - '8125:8125'

networks:
  telegraf-influx-network:
    driver: bridge